version: 2.1

# Jobs define the individual tasks that will be run as part of the workflow.
jobs:
  build:
    # Specifies the Docker image to use for the job.
    docker:
      - image: cimg/openjdk:17.0

    # Steps define the commands that will be run in the job.
    steps:
      # Checks out the repository code.
      - checkout
      # Installs the gpsUtil dependency.
      - run:
          name: Install gpsUtil Dependency
          command: mvn install:install-file -Dfile=./libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
      # Installs the RewardCentral dependency.
      - run:
          name: Install RewardCentral Dependency
          command: mvn install:install-file -Dfile=./libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
      # Installs the TripPricer dependency.
      - run:
          name: Install TripPricer Dependency
          command: mvn install:install-file -Dfile=./libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
      # Runs the Maven clean and package goals to build the project.
      - run:
          name: Build Project
          command: mvn clean package

  test:
    # Specifies the Docker image to use for the job.
    docker:
      - image: cimg/openjdk:17.0

    # Steps define the commands that will be run in the job.
    steps:
      # Checks out the repository code.
      - checkout
      # Installs the gpsUtil dependency.
      - run:
          name: Install gpsUtil Dependency
          command: mvn install:install-file -Dfile=./libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
      # Installs the RewardCentral dependency.
      - run:
          name: Install RewardCentral Dependency
          command: mvn install:install-file -Dfile=./libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
      # Installs the TripPricer dependency.
      - run:
          name: Install TripPricer Dependency
          command: mvn install:install-file -Dfile=./libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
      # Runs the Maven test goal to execute the tests.
      - run:
          name: Run Tests
          command: mvn test

# Workflows define the order in which jobs are run.
workflows:
  version: 2
  build_and_test:
    jobs:
      # Runs the build job.
      - build
      # Runs the test job, but only after the build job has completed successfully.
      - test:
          requires:
            - build
